#!/usr/bin/python
#Requires numpy to be installed. re and sys are defaults for python
#assumes python 2.7
import os
import sys
import numpy as np
import re
from sys import argv
# Main function
def trodesBinaryLayout(filename):
    """Where the samples start and how they are laid out, without reading any.

    Trodes writes an ASCII settings header followed by plain interleaved samples,
    so the payload can be handed straight to a file-backed reader instead of being
    loaded. Returns dict(offset, dtype, n_channels, n_samples), or None when the
    record is not a single interleaved field — the caller should then fall back to
    the structured reader.
    """
    with open(filename, 'rb') as f:
        if f.readline().decode('ascii').strip() != '<Start settings>':
            raise Exception("Settings format not supported")
        fieldsText = {}
        for line in f:
            line = line.decode('ascii').strip()
            if line == '<End settings>':
                break
            vals = line.split(': ')
            fieldsText.update({vals[0].lower(): vals[1]})
        dt = parseFields(fieldsText['fields'])
        offset = f.tell()

    # Only a lone "<voltage N*int16>" record is a plain interleaved block. Anything
    # else (a time field, mixed types) has gaps a flat reader would misinterpret.
    if dt.names is None or len(dt.names) != 1:
        return None
    sub, sub_offset = dt.fields[dt.names[0]][0], dt.fields[dt.names[0]][1]
    if sub_offset != 0 or sub.subdtype is None:
        return None
    base, shape = sub.subdtype
    if len(shape) != 1:
        return None
    n_bytes = os.path.getsize(filename) - offset
    return {'offset': offset, 'dtype': base, 'n_channels': int(shape[0]),
            'n_samples': int(n_bytes // dt.itemsize)}


def readTrodesExtractedDataFile(filename, memmap=False):
    """Read a Trodes extracted .dat file.

    memmap=True returns the samples as a read-only np.memmap instead of loading
    them. A 128-channel hour-long recording is ~27 GiB as int16, which does not fit
    in RAM on these machines; memory-mapping lets the sorter stream it in chunks
    while behaving like an ordinary array."""
    with open(filename, 'rb') as f:
        # Check if first line is start of settings block
        if f.readline().decode('ascii').strip() != '<Start settings>':
            raise Exception("Settings format not supported")
        fields = True
        fieldsText = {}
        for line in f:
            # Read through block of settings
            if(fields):
                line = line.decode('ascii').strip()
                # filling in fields dict
                if line != '<End settings>':
                    vals = line.split(': ')
                    fieldsText.update({vals[0].lower(): vals[1]})
                # End of settings block, signal end of fields
                else:
                    fields = False
                    dt = parseFields(fieldsText['fields'])
                    fieldsText['data'] = np.zeros([1], dtype = dt)
                    break
        # Reads rest of file, using dtype format generated by parseFields()
        dt = parseFields(fieldsText['fields'])
        if memmap:
            # BufferedReader.tell() is the logical position, so it is the true first
            # byte of the payload even though the header was read line by line.
            offset = f.tell()
            # Count whole records ourselves. np.fromfile quietly drops a partial
            # trailing record (an interrupted acquisition leaves one), but np.memmap
            # raises "Size of available data is not a multiple of the data-type
            # size" — so pass an explicit shape to keep the old behaviour.
            n_records = (os.path.getsize(filename) - offset) // dt.itemsize
            data = np.memmap(filename, dtype=dt, mode='r', offset=offset,
                             shape=(int(n_records),))
        else:
            data = np.fromfile(f, dt)
        fieldsText.update({'data': data})
        return fieldsText


# Parses last fields parameter (<time uint32><...>) as a single string
# Assumes it is formatted as <name number * type> or <name type>
# Returns: np.dtype
def parseFields(fieldstr):
    # Returns np.dtype from field string
    sep = re.split(r'\s', re.sub(r"\>\<|\>|\<", ' ', fieldstr).strip())
    # print(sep)
    typearr = []
    # Every two elmts is fieldname followed by datatype
    for i in range(0,sep.__len__(), 2):
        fieldname = sep[i]
        repeats = 1
        ftype = 'uint32'
        # Finds if a <num>* is included in datatype
        if sep[i+1].__contains__('*'):
            temptypes = re.split(r'\*', sep[i+1])
            # Results in the correct assignment, whether str is num*dtype or dtype*num
            ftype = temptypes[temptypes[0].isdigit()]
            repeats = int(temptypes[temptypes[1].isdigit()])
        else:
            ftype = sep[i+1]
        try:
            fieldtype = getattr(np, ftype)
        except AttributeError:
            print(ftype + " is not a valid field type.\n")
            exit(1)
        else:
            # Scalar fields use (name, type); (name, type, 1) triggers a numpy
            # FutureWarning and will later be reinterpreted as shape (1,).
            if repeats == 1:
                typearr.append((str(fieldname), fieldtype))
            else:
                typearr.append((str(fieldname), fieldtype, repeats))
    return np.dtype(typearr)



# Testing function here---------------------
# fields = readTrodesExtractedDataFile('16ChannelRec.spikes_nt10.dat')
# print(fields['data'])

# --- REPLACE WITH THIS ---
if __name__ == "__main__":
    import sys
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    if '--info' in sys.argv and args:
        # Memory-map and report shape only. Safe on the big recordings, where
        # printing the array (below) would try to render tens of GiB.
        fields = readTrodesExtractedDataFile(args[0], memmap=True)
        v = fields['data']['voltage']
        print("file     : {}".format(args[0]))
        print("samples  : {}".format(v.shape[0]))
        print("channels : {}".format(v.shape[1] if v.ndim > 1 else 1))
        print("dtype    : {}  ({})".format(v.dtype, type(v).__name__))
        print("size     : {:.1f} GiB on disk, mapped not loaded".format(v.nbytes / 2**30))
    elif args:
        np.set_printoptions(threshold=sys.maxsize)
        fields = readTrodesExtractedDataFile(args[0])
        print(fields['data'])
    else:
        print("usage: readTrodesExtractedDataFile3.py [--info] <file.dat>")

